### ISSUE TITLE
Base Panel 400 front X-axis distance larger than distance between profiles

### ISSUE THREAD

**Issue by Angznugen** [Rat-Rig/V-core-3#45]
Base panel Front X-axis edges are 540.150mm while the distance between profiles are 540mm
![image](https://user-images.githubusercontent.com/91319683/134658100-55c6731f-b762-433d-a30a-5b17d1e407a9.png)
![image](https://user-images.githubusercontent.com/91319683/134658139-300509ba-9a2f-4955-92b1-7a444399356b.png)

**Comment by nexx** [comment]
This was due to the DXF files accounting for laser kerf.

#46 updates all DXF files to be exact dimensions, leaving the compensation of laser kerf down to the operator of the laser cutter. Further, STEP files are now available for all panels which can be directly imported into CAD software.
