### ISSUE TITLE
lead_screw_motor_cage_back doesn't allow motor repositioning

### ISSUE THREAD

**Issue by ShuttleworthM** [Rat-Rig/V-core-3#59]
In the previous version of the lead_screw_motor_cage_back part, the rear z-axis motor could be slid back and forth in its mount to allow for leadscrew alignment. In the latest version, the slots to allow this sliding action and the build guide indicate that the motor should be able to move; however, the material that has been added to the mount prevents this.

I am not sure if this is a problem or just a leftover from the previous iteration, please advise.

**Comment by pkucmus** [comment]
It's fixed now. Thanks!
